name: Sync to Azure DevOps

on:
  push:
    branches:
      - master  
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "tejaswinikakade"
          git config --global user.email "tejukakade1821@gmail.com"

      - name: Push to Azure DevOps
        run: |
          git remote add azure https://${{ secrets.tkakade }}:${{ secrets.AZURE_PAT }}@${{ secrets.secrets.AZURE_REPO_URL }}
          git push azure HEAD:refs/heads/master
